// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forum_module.proxies;

public class Comment
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject commentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Forum_Module.Comment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		Submitted("Submitted"),
		Comment_Question("Forum_Module.Comment_Question");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Comment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Comment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject commentMendixObject)
	{
		if (commentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, commentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.commentMendixObject = commentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Comment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static forum_module.proxies.Comment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return forum_module.proxies.Comment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static forum_module.proxies.Comment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forum_module.proxies.Comment(context, mendixObject);
	}

	public static forum_module.proxies.Comment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forum_module.proxies.Comment.initialize(context, mendixObject);
	}

	public static java.util.List<forum_module.proxies.Comment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> forum_module.proxies.Comment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Submitted
	 */
	public final java.util.Date getSubmitted()
	{
		return getSubmitted(getContext());
	}

	/**
	 * @param context
	 * @return value of Submitted
	 */
	public final java.util.Date getSubmitted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Submitted.toString());
	}

	/**
	 * Set value of Submitted
	 * @param submitted
	 */
	public final void setSubmitted(java.util.Date submitted)
	{
		setSubmitted(getContext(), submitted);
	}

	/**
	 * Set value of Submitted
	 * @param context
	 * @param submitted
	 */
	public final void setSubmitted(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date submitted)
	{
		getMendixObject().setValue(context, MemberNames.Submitted.toString(), submitted);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Comment_Question
	 */
	public final forum_module.proxies.Question getComment_Question() throws com.mendix.core.CoreException
	{
		return getComment_Question(getContext());
	}

	/**
	 * @param context
	 * @return value of Comment_Question
	 * @throws com.mendix.core.CoreException
	 */
	public final forum_module.proxies.Question getComment_Question(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		forum_module.proxies.Question result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Comment_Question.toString());
		if (identifier != null) {
			result = forum_module.proxies.Question.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Comment_Question
	 * @param comment_question
	 */
	public final void setComment_Question(forum_module.proxies.Question comment_question)
	{
		setComment_Question(getContext(), comment_question);
	}

	/**
	 * Set value of Comment_Question
	 * @param context
	 * @param comment_question
	 */
	public final void setComment_Question(com.mendix.systemwideinterfaces.core.IContext context, forum_module.proxies.Question comment_question)
	{
		if (comment_question == null) {
			getMendixObject().setValue(context, MemberNames.Comment_Question.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Comment_Question.toString(), comment_question.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return commentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forum_module.proxies.Comment that = (forum_module.proxies.Comment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
