// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forum_module.proxies;

public class Question
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject questionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Forum_Module.Question";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		Submitted("Submitted"),
		LastActivity("LastActivity"),
		ViewCount("ViewCount"),
		ResponseCount("ResponseCount"),
		Question_Spaces("Forum_Module.Question_Spaces"),
		Question_Question("Forum_Module.Question_Question"),
		Question_Label("Forum_Module.Question_Label");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Question(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Question(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject questionMendixObject)
	{
		if (questionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, questionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.questionMendixObject = questionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Question.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static forum_module.proxies.Question initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return forum_module.proxies.Question.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static forum_module.proxies.Question initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forum_module.proxies.Question(context, mendixObject);
	}

	public static forum_module.proxies.Question load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forum_module.proxies.Question.initialize(context, mendixObject);
	}

	public static java.util.List<forum_module.proxies.Question> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> forum_module.proxies.Question.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Submitted
	 */
	public final java.util.Date getSubmitted()
	{
		return getSubmitted(getContext());
	}

	/**
	 * @param context
	 * @return value of Submitted
	 */
	public final java.util.Date getSubmitted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Submitted.toString());
	}

	/**
	 * Set value of Submitted
	 * @param submitted
	 */
	public final void setSubmitted(java.util.Date submitted)
	{
		setSubmitted(getContext(), submitted);
	}

	/**
	 * Set value of Submitted
	 * @param context
	 * @param submitted
	 */
	public final void setSubmitted(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date submitted)
	{
		getMendixObject().setValue(context, MemberNames.Submitted.toString(), submitted);
	}

	/**
	 * @return value of LastActivity
	 */
	public final java.util.Date getLastActivity()
	{
		return getLastActivity(getContext());
	}

	/**
	 * @param context
	 * @return value of LastActivity
	 */
	public final java.util.Date getLastActivity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastActivity.toString());
	}

	/**
	 * Set value of LastActivity
	 * @param lastactivity
	 */
	public final void setLastActivity(java.util.Date lastactivity)
	{
		setLastActivity(getContext(), lastactivity);
	}

	/**
	 * Set value of LastActivity
	 * @param context
	 * @param lastactivity
	 */
	public final void setLastActivity(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastactivity)
	{
		getMendixObject().setValue(context, MemberNames.LastActivity.toString(), lastactivity);
	}

	/**
	 * @return value of ViewCount
	 */
	public final java.lang.Integer getViewCount()
	{
		return getViewCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewCount
	 */
	public final java.lang.Integer getViewCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ViewCount.toString());
	}

	/**
	 * Set value of ViewCount
	 * @param viewcount
	 */
	public final void setViewCount(java.lang.Integer viewcount)
	{
		setViewCount(getContext(), viewcount);
	}

	/**
	 * Set value of ViewCount
	 * @param context
	 * @param viewcount
	 */
	public final void setViewCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer viewcount)
	{
		getMendixObject().setValue(context, MemberNames.ViewCount.toString(), viewcount);
	}

	/**
	 * @return value of ResponseCount
	 */
	public final java.lang.Integer getResponseCount()
	{
		return getResponseCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseCount
	 */
	public final java.lang.Integer getResponseCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResponseCount.toString());
	}

	/**
	 * Set value of ResponseCount
	 * @param responsecount
	 */
	public final void setResponseCount(java.lang.Integer responsecount)
	{
		setResponseCount(getContext(), responsecount);
	}

	/**
	 * Set value of ResponseCount
	 * @param context
	 * @param responsecount
	 */
	public final void setResponseCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer responsecount)
	{
		getMendixObject().setValue(context, MemberNames.ResponseCount.toString(), responsecount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Question_Spaces
	 */
	public final forum_module.proxies.Spaces getQuestion_Spaces() throws com.mendix.core.CoreException
	{
		return getQuestion_Spaces(getContext());
	}

	/**
	 * @param context
	 * @return value of Question_Spaces
	 * @throws com.mendix.core.CoreException
	 */
	public final forum_module.proxies.Spaces getQuestion_Spaces(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		forum_module.proxies.Spaces result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Question_Spaces.toString());
		if (identifier != null) {
			result = forum_module.proxies.Spaces.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Question_Spaces
	 * @param question_spaces
	 */
	public final void setQuestion_Spaces(forum_module.proxies.Spaces question_spaces)
	{
		setQuestion_Spaces(getContext(), question_spaces);
	}

	/**
	 * Set value of Question_Spaces
	 * @param context
	 * @param question_spaces
	 */
	public final void setQuestion_Spaces(com.mendix.systemwideinterfaces.core.IContext context, forum_module.proxies.Spaces question_spaces)
	{
		if (question_spaces == null) {
			getMendixObject().setValue(context, MemberNames.Question_Spaces.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Question_Spaces.toString(), question_spaces.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Question_Question
	 */
	public final forum_module.proxies.Question getQuestion_Question() throws com.mendix.core.CoreException
	{
		return getQuestion_Question(getContext());
	}

	/**
	 * @param context
	 * @return value of Question_Question
	 * @throws com.mendix.core.CoreException
	 */
	public final forum_module.proxies.Question getQuestion_Question(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		forum_module.proxies.Question result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Question_Question.toString());
		if (identifier != null) {
			result = forum_module.proxies.Question.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Question_Question
	 * @param question_question
	 */
	public final void setQuestion_Question(forum_module.proxies.Question question_question)
	{
		setQuestion_Question(getContext(), question_question);
	}

	/**
	 * Set value of Question_Question
	 * @param context
	 * @param question_question
	 */
	public final void setQuestion_Question(com.mendix.systemwideinterfaces.core.IContext context, forum_module.proxies.Question question_question)
	{
		if (question_question == null) {
			getMendixObject().setValue(context, MemberNames.Question_Question.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Question_Question.toString(), question_question.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Question_Label
	 */
	public final java.util.List<forum_module.proxies.Label> getQuestion_Label() throws com.mendix.core.CoreException
	{
		return getQuestion_Label(getContext());
	}

	/**
	 * @param context
	 * @return value of Question_Label
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<forum_module.proxies.Label> getQuestion_Label(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<forum_module.proxies.Label> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Question_Label.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(forum_module.proxies.Label.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Question_Label
	 * @param question_label
	 */
	public final void setQuestion_Label(java.util.List<forum_module.proxies.Label> question_label)
	{
		setQuestion_Label(getContext(), question_label);
	}

	/**
	 * Set value of Question_Label
	 * @param context
	 * @param question_label
	 */
	public final void setQuestion_Label(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<forum_module.proxies.Label> question_label)
	{
		var identifiers = question_label
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Question_Label.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return questionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forum_module.proxies.Question that = (forum_module.proxies.Question) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
