// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forum_module.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Forum_Module module
	public static boolean aCT_Question_NewEdit(IContext context, forum_module.proxies.Question _newQuestion)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NewQuestion", _newQuestion == null ? null : _newQuestion.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Forum_Module.ACT_Question_NewEdit").withParams(params).execute(context);
	}
	public static java.util.List<forum_module.proxies.Comment> comment_DisplayALL(IContext context, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Question", _question == null ? null : _question.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Forum_Module.Comment_DisplayALL").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> forum_module.proxies.Comment.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void comment_New(IContext context, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Question", _question == null ? null : _question.getMendixObject());
		Core.microflowCall("Forum_Module.Comment_New").withParams(params).execute(context);
	}
	public static void comment_Submit(IContext context, forum_module.proxies.Comment _comment, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Comment", _comment == null ? null : _comment.getMendixObject());
		params.put("Question", _question == null ? null : _question.getMendixObject());
		Core.microflowCall("Forum_Module.Comment_Submit").withParams(params).execute(context);
	}
	public static void dELETE_EVERYTHING(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Forum_Module.DELETE_EVERYTHING").withParams(params).execute(context);
	}
	public static void question_Delete(IContext context, forum_module.proxies.Question _newQuestion)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NewQuestion", _newQuestion == null ? null : _newQuestion.getMendixObject());
		Core.microflowCall("Forum_Module.Question_Delete").withParams(params).execute(context);
	}
	public static java.util.List<forum_module.proxies.Question> question_DisplayALL(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Forum_Module.Question_DisplayALL").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> forum_module.proxies.Question.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<forum_module.proxies.Label> question_Get_Labels(IContext context, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Question", _question == null ? null : _question.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Forum_Module.Question_Get_Labels").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> forum_module.proxies.Label.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static forum_module.proxies.Spaces question_Get_Space(IContext context, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Question", _question == null ? null : _question.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Forum_Module.Question_Get_Space").withParams(params).execute(context);
		return result == null ? null : forum_module.proxies.Spaces.initialize(context, result);
	}
	public static void question_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Forum_Module.Question_New").withParams(params).execute(context);
	}
	public static void question_View(IContext context, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Question", _question == null ? null : _question.getMendixObject());
		Core.microflowCall("Forum_Module.Question_View").withParams(params).execute(context);
	}
	public static java.util.List<forum_module.proxies.Question> response_DisplayALL(IContext context, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Question", _question == null ? null : _question.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Forum_Module.Response_DisplayALL").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> forum_module.proxies.Question.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static forum_module.proxies.Question response_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Forum_Module.Response_New").withParams(params).execute(context);
		return result == null ? null : forum_module.proxies.Question.initialize(context, result);
	}
	public static void response_Remove(IContext context, forum_module.proxies.Question _response, forum_module.proxies.Question _question)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Question", _question == null ? null : _question.getMendixObject());
		Core.microflowCall("Forum_Module.Response_Remove").withParams(params).execute(context);
	}
	public static void response_Submit(IContext context, forum_module.proxies.Question _question, forum_module.proxies.Question _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Question", _question == null ? null : _question.getMendixObject());
		params.put("Response", _response == null ? null : _response.getMendixObject());
		Core.microflowCall("Forum_Module.Response_Submit").withParams(params).execute(context);
	}
	public static void user_getInfo(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Forum_Module.user_getInfo").withParams(params).execute(context);
	}
	public static boolean vAL_Question_NewEdit(IContext context, forum_module.proxies.Question _newQuestion)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NewQuestion", _newQuestion == null ? null : _newQuestion.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Forum_Module.VAL_Question_NewEdit").withParams(params).execute(context);
	}
}
